name: BULISP
channels: #might need to add additional channels
  - pytorch
  - conda-forge
  - nodefaults
dependencies:
  # Stuff specific to our forecaster
  - pytorch
  - cudatoolkit=11.3
  # From atd2022
  # Core
  - python>=3.9,<3.10
  - bokeh>=2.4.2
  - holoviews>=1.14.8
  - matplotlib>=3.3.2
  - numpy==1.21.5
  - pandas>=1.3.5,<1.4
  - panel>=0.12.7
  - scikit-learn>=0.24.1
  - scipy==1.7.3
  - seaborn>=0.11.2
  - sktime>=0.11
  - tqdm>=4.63.0
  # Testing
  - black>=22.3.0
  - flake8>=3.9.2,<4
  - hypothesis>=6.41.0
  - isort>=5.10.1
  - mypy>=0.942
  - nb-clean>=2.1.0
  - nbqa>=1.3.1
  - pandas-stubs>=1.2.0.56
  - pydocstyle>=6.1.1
  - pytest>=6.2.5,<7
  - pytest-flake8>=1.1.0
  # Nice to haves
  - ipykernel>=6.12.0
  - ipywidgets>=7.7.0
  - notebook>=6.4.10
  # atd2022 and our local package
  - pip>=22.0.4
  - pip:
    # - git+https://gitlab.com/algorithms-for-threat-detection/2022/atd2022.git  # install atd2022 from Gitlab (https)
    - git+ssh://git@gitlab.com/algorithms-for-threat-detection/2022/atd2022.git  # install atd2022 from Gitlab (ssh)
    - -e .[all]  # install our local arlpsu_ml package in editable mode (so it's easy for me to make changes during development)
